# -*- coding: utf-8 -*-
"""cleaned_hotel_bookings .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tEBpE7XhQ-Wuaya_OdUe8fZ_xkrnzkko
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/hotel_bookings.csv')
df

df.info()

df.describe()

df.dtypes

df.duplicated().sum()

Null_Value = df.isnull().sum()
Null_Value

Missing_Value = df.isnull().sum()
Missing_Value = Missing_Value[Missing_Value > 0]
Missing_Value

df.drop(columns="company",inplace=True)

df.columns

df.duplicated().sum()

df.isnull().sum()

df["children"] = df["children"].fillna(df["children"].mean())

df["children"] = df["children"].astype(int)

df.dtypes

df["agent"] = pd.to_numeric(df["agent"],errors="coerce")

df.dtypes

df["agent"] = df["agent"].fillna(0)

df["agent"] = df["agent"].astype(int)

df.isnull().sum()

Most_Common_country = df["country"].mode()[0]
df["country"]=df["country"].fillna(Most_Common_country)

df.isnull().sum()

df.duplicated().sum()

df.drop_duplicates(inplace=True)

df.duplicated().sum()

(df.isnull().sum()/df.shape[0])*100

adr_per_hotel = df.groupby("hotel")["adr"].mean()
plt.pie(adr_per_hotel, labels=adr_per_hotel.index, autopct="%1.1f%%")
plt.title("Average Daily Rate per Hotel Type")
plt.show()

plt.figure(figsize=(8,5))
sns.countplot(data=df, x='hotel')
plt.title('Number of Bookings per Hotel Type')
plt.xlabel('Hotel Type')
plt.ylabel('Number of Bookings')
plt.show()

hotel_cancel = df.groupby(['hotel', 'is_canceled']).size().reset_index(name='count')
hotel_total = hotel_cancel.groupby('hotel')['count'].transform('sum')
hotel_cancel['percentage'] = hotel_cancel['count'] / hotel_total

plt.figure(figsize=(8,5))
sns.barplot(data=hotel_cancel, x='hotel', y='percentage', hue='is_canceled', palette='Set1')
plt.title('Cancellation Rate by Hotel Type', fontsize=14)
plt.ylabel('Percentage')
plt.xlabel('Hotel Type')
plt.legend(title='Canceled', loc='upper right')
sns.despine()
plt.show()

plt.figure(figsize=(12,6))
order = ['January','February','March','April','May','June','July','August','September','October','November','December']
sns.countplot(data=df, x='arrival_date_month', order=order, palette='mako')
plt.title('Monthly Bookings', fontsize=14)
plt.xlabel('Month')
plt.ylabel('Number of Bookings')
plt.xticks(rotation=45)
sns.despine()
plt.show()

plt.figure(figsize=(14,10))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Heatmap')
plt.show()

plt.figure(figsize=(10,6))
sns.kdeplot(df['stays_in_week_nights'], fill=True, label='Week Nights', color='navy', alpha=0.5)
sns.kdeplot(df['stays_in_weekend_nights'], fill=True, label='Weekend Nights', color='orange', alpha=0.5)
plt.title('Stay Duration Distribution', fontsize=14)
plt.xlabel('Nights')
plt.ylabel('Density')
plt.legend()
sns.despine()
plt.show()

top_countries = df['country'].value_counts().nlargest(10).reset_index()
top_countries.columns = ['country', 'bookings']

plt.figure(figsize=(10,6))
sns.barplot(data=top_countries, x='country', y='bookings', palette='viridis')
plt.title('Top 10 Countries by Number of Bookings', fontsize=14)
plt.xlabel('Country')
plt.ylabel('Bookings')
sns.despine()
plt.show()

plt.figure(figsize=(8,5))
sns.countplot(data=df, x='customer_type', hue='is_canceled', palette='pastel')
plt.title('Customer Type vs Cancellation', fontsize=14)
plt.xlabel('Customer Type')
plt.ylabel('Count')
plt.legend(title='Canceled')
sns.despine()
plt.show()

plt.figure(figsize=(12,6))
sns.countplot(data=df, x='market_segment', hue='distribution_channel', palette='Set3')
plt.title('Market Segment vs Distribution Channel', fontsize=14)
plt.xlabel('Market Segment')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.legend(title='Distribution Channel')
sns.despine()
plt.show()

plt.figure(figsize=(10,6))
sns.violinplot(data=df, x='reserved_room_type', y='adr', palette='cubehelix')
plt.title('ADR by Reserved Room Type', fontsize=14)
plt.xlabel('Room Type')
plt.ylabel('ADR')
sns.despine()
plt.show()

lead_adr = df.groupby(['lead_time', 'is_canceled'])['adr'].mean().reset_index()

plt.figure(figsize=(12,6))
sns.lineplot(data=lead_adr, x='lead_time', y='adr', hue='is_canceled', palette='coolwarm')
plt.title('ADR vs Lead Time by Cancellation Status', fontsize=14)
plt.xlabel('Lead Time (days)')
plt.ylabel('Average ADR')
plt.legend(title='Canceled')
sns.despine()
plt.show()

df.to_csv("cleane_hotel_bookings.csv",index=False)